Add towns to states
civica-digital/api-estados pull request #1
Opened 2017-01-30 15:25 UTC by mikesaurio

2017-01-30 17:11 UTC, Gidrek commented on api/priv/repo/seeds.exs
> +
Las demás líneas no deben ir identadas, si es una nueva instrucción debe estar a la izquierda

2017-01-30 17:11 UTC, Gidrek commented on api/web/controllers/state_controller.ex
> +
Borrar el espacio en blanco

2017-01-30 17:12 UTC, Gidrek commented on api/web/models/town.ex
> +
Borrar espacio en blanco

2017-01-30 17:12 UTC, Gidrek commented on api/web/router.ex
> +
Borrar un espacio en blanco

2017-01-30 17:13 UTC, Gidrek requested changes
He puesto unos comentarios, más que nada de style coding

2017-01-30 17:48 UTC, Gidrek commented on api/web/models/town.ex
> +end
Fin del archivo con espacio en blanco

2017-02-07 21:45 UTC, ricalanis commented
Qué bonito se ve elixir, raza! Keep it up!

2017-02-07 21:57 UTC, Gidrek commented on api/lib/data.ex
> +  #Data.load_csv
Si no pones documentacion del modulo, mejor quitar este comentario. Puedes ponerle documentacion al modulo con

```
@moduledoc """
Module documentation in markdown
"""
```

2017-02-08 04:08 UTC, merged